### ISSUE TITLE
efibootdump.c -Werror,-Wpointer-sign

### ISSUE THREAD

**Issue by tpgxyz** [rhboot/efibootmgr#134] opened 2020-07-01 23:00 UTC
Trying to compile efibootmgr-17 with LLVM/clang-10.x

```
make[1]: Entering directory '/builddir/build/BUILD/efibootmgr-17/src'
/usr/bin/clang   -Os -fomit-frame-pointer -g1 -Wstrict-aliasing=2 -pipe -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fstack-protector-all --param=ssp-buffer-size=4 -m64 -mtune=generic -flto -Oz -I/builddir/build/BUILD/efibootmgr-17/src/include -Werror -Wall -Wextra -Wsign-compare -Wstrict-aliasing -std=gnu11 -fPIC -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -DLOCALEDIR=\"/usr/share/locale/\" -DEFIBOOTMGR_VERSION="\"17\"" -DDEFAULT_LOADER=\"\\\\EFI\\\\openmandriva\\\\grub64.efi\"   -I/usr/include/efivar   -c -o efibootdump.o efibootdump.c
make[1]: Leaving directory '/builddir/build/BUILD/efibootmgr-17/src'
efibootdump.c:72:32: error: passing 'char *' to parameter of type 'unsigned char *' converts between pointers to integer types with different sign [-Werror,-Wpointer-sign]
        rc = efidp_format_device_path(text_path, text_path_len,
                                      ^~~~~~~~~
/usr/include/efivar/efivar-dp.h:1234:56: note: passing argument to parameter 'buf' here
extern ssize_t efidp_format_device_path(unsigned char *buf, size_t size,
                                                       ^
1 error generated.
make[1]: *** [/builddir/build/BUILD/efibootmgr-17/Make.rules:32: efibootdump.o] Error 1
```

```
/usr/bin/clang   -Os -fomit-frame-pointer -g1 -Wstrict-aliasing=2 -pipe -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fstack-protector-all --param=ssp-buffer-size=4 -m64 -mtune=generic -flto -Oz -I/builddir/build/BUILD/efibootmgr-17/src/include -Werror -Wall -Wextra -Wsign-compare -Wstrict-aliasing -std=gnu11 -fPIC -D_FILE_OFFSET_BITS=64 -D_GNU_SOURCE -DLOCALEDIR=\"/usr/share/locale/\" -DEFIBOOTMGR_VERSION="\"17\"" -DDEFAULT_LOADER=\"\\\\EFI\\\\openmandriva\\\\grub64.efi\"   -I/usr/include/efivar   -c -o efibootmgr.o efibootmgr.c
make[1]: Leaving directory '/builddir/build/BUILD/efibootmgr-17/src'
efibootmgr.c:952:34: error: passing 'char *' to parameter of type 'unsigned char *' converts between pointers to integer types with different sign [-Werror,-Wpointer-sign]
                        rc = efidp_format_device_path(text_path, text_path_len,
                                                      ^~~~~~~~~
/usr/include/efivar/efivar-dp.h:1234:56: note: passing argument to parameter 'buf' here
extern ssize_t efidp_format_device_path(unsigned char *buf, size_t size,
                                                       ^
efibootmgr.c:963:34: error: passing 'char *' to parameter of type 'unsigned char *' converts between pointers to integer types with different sign [-Werror,-Wpointer-sign]
                        rc = efidp_format_device_path(text_path, text_path_len,
                                                      ^~~~~~~~~
/usr/include/efivar/efivar-dp.h:1234:56: note: passing argument to parameter 'buf' here
extern ssize_t efidp_format_device_path(unsigned char *buf, size_t size,
                                                       ^
2 errors generated.
make[1]: *** [/builddir/build/BUILD/efibootmgr-17/Make.rules:32: efibootmgr.o] Error 1
```

**Comment by martinezjavier** [comment] 2021-06-17 10:15
Duplicate of issue #118.

**Closed by martinezjavier** 2021-06-17 10:15 UTC
