### ISSUE TITLE
boot order not saved/overwritten on reboot

### ISSUE THREAD

**Issue by barjac** [rhboot/efibootmgr#19] opened 2014-10-23 23:02 UTC
The title is probably inaccurate but the effect is that a boot order set up in efibootmgr is ignored on next boot.
Here is an extract from https://bugs.mageia.org/show_bug.cgi?id=14140

> Installed efibootmgr-0.11.0-1.mga5.
> 1. Check current boot order:
>    efibootmgr
>    BootCurrent: 0001
>    Timeout: 3 seconds
>    BootOrder: 0002,0001
>    Boot0001\* mageia
>    Boot0002\* Windows Boot Manager
> 2. Delete boot order:
>    efibootmgr -O
>    BootCurrent: 0001
>    Timeout: 3 seconds
>    Boot0001\* mageia
>    Boot0002\* Windows Boot Manager
> 3. Set Mageia first in boot order:
>    efibootmgr -o 1,2
>    BootCurrent: 0001
>    Timeout: 3 seconds
>    BootOrder: 0001,0002
>    Boot0001\* mageia
>    boot0002\* Windows Boot Manager
> 
> But when I reboot, Windows still boots by default. When I boot into Mageia,
> I see the same as in (1), i.e. changes has not been actually saved.

Any thoughts on what may be happening here?

**Comment by excieve** [comment] 2015-01-27 20:16
Same problem on Acer Aspire VN7-591G and BIOS Insyde V1.10.
Had to resort to this [ugly hack](https://communities.intel.com/thread/43629) (concealing the Windows boot manager), after which configured boot order is fully respected.

**Comment by creynold** [comment] 2015-09-11 19:35
Same issue on Lenovo Thinkstation p300

**Comment by biggreenogre** [comment] 2015-09-30 15:56
Perhaps not quite the same issue?
Supermicro server with _NO_ MS Windows installed. (AMI BIOS)
Ubuntu 14.04 trusty with two ESP partitions. Either ESP will boot to root file system (RAID1 on partition 2 of each disk)
Setting the BootOrder with efibootmgr appears to work (second run of efibootmgr reports correct settings) but the system ignores any changes on next boot.
I can add/remove boot entries and BootNext works as expected.

Ubuntu 14.04 trusty - fully updated
Kernel 3.13.0-65-generic

Tried:
Stock Ubuntu 14.04 (no efivar module):-
efibootmgr_0.5.4-7ubuntu1.2 - stock Ubuntu 14.04
From Ubuntu repos for later releases:-
efibootmgr_0.7.0-2ubuntu0.14.10.1 with libefivar0_0.10-5 and efivar_0.10-5
efibootmgr_0.11.0-3 with libefivar0_0.15-3 and efivar_0.15-3
efibootmgr_0.12-4 with libefivar0_0.21-1 and efivar_0.21-1

The later versions were also using the stock Ubuntu kernel with no efivar module

Should I be talking to Supermicro about this?

**Comment by barjac** [comment] 2015-09-30 21:51
I'm wondering if any of these issues are related to a problem I had recently with an "Acer Aspire E15 Start" laptop.
With Secure Boot OFF the laptop always just showed a screen saying "No Bootable Device". Even after re-installing grub2 to the HD and checking that mageia was first in the boot order, it failed to boot and on re-checking the boot order, mageia had been removed from the boot order by the boot attempt.
It had a clean install of Mageia 5 on the drive which was fine and could be booted via a SuperGrub2 CD.
The problem turned out to be a buggy UEFI BIOS whereby it required grubx64.efi to be set as "trusted" even when Secure Boot was not being used.
The solution was to enter a password and set Secure Boot ON, then set the mageia/grubx64.efi as trusted. The machine then booted correctly with or without Secure Boot enabled and with or without a Secure Boot password set.
This seems to be a common issue with some Acer laptops, maybe it affects other manufacturers.

**Comment by biggreenogre** [comment] 2015-10-15 15:33
Follow up on my post above:
In our case, efibootmgr is behaving correctly as per the UEFI spec. (thank you, vathpela and others!) The issue lies with Supermicro who have not implemented the UEFI spec correctly on these systems. The firmware ignores the UEFI BootOrder variable completely on boot. Supermicro tech support say that this is due to their "standard" BIOS boot menu system and will not fix it.
I am not aware of any workaround for this issue.

**Comment by wind0204** [comment] 2016-04-20 17:01
I've got the same issue on my new laptop, and I just found a workaround, that is to make it run 'efibootmgr -n NNNN' every time it boots. I would like somebody to hack this lame BIOS if possible!

Laptop : Acer Aspire V-13, V3-372-P5E5
BIOS version : 1.05
BIOS name : InsydeH2O Setup Utility        Rev. 5.0
efibootmgr version : 0.12

**Comment by PlasmaPower** [comment] 2016-04-23 03:04
@wind0204 Have you found a permanent workaround? I'm in the same situation here.

**Comment by PlasmaPower** [comment] 2016-04-23 03:23
@wind0204 I figured it out! You need to enable secure boot and register systemd with secure boot. However, then it complained that vm-linuz wasn't registered so I disabled secure boot again. It kept Linux on the boot menu though, so I moved it up to first and everything worked out. I might look into getting secure boot working with a chain efi loader though.

**Comment by wind0204** [comment] 2016-04-23 10:36
@PlasmaPower Thanx for sharing :) I still don't know what's going on in **this stupid motherboard in V3-372** but anyway, now I've somehow managed to get it to boot without an efi bootable drive plugged in, I don't know how it works though.

I still use the udev rule for running 'efibootmgr -n NNNN' but this time I've got the stupid motherboard to register my linux kernel by renaming the kernel to ?????.efi and then registering the hash by entering the BIOS setup utility(holding down the key F2 when it's doing a POST)->'Security'->'Select AN UEFI file as trusted for executing'->browse and choose the kernel I just renamed.-I'd tried ArchISO's Hashtool but it wouldn't stop the BIOS printing cute image and text of security check failure- After the registering the hash in BIOS setup utility, this motherboard had got the efi variable and it appeared on the boot priority configuration screen but since it didn't have the kernel parameters (root, resume, resume_offset, initrd) it just panicked.

the next step is build a kernel with built-in kernel parameters and get rid of the udev rule. *sigh*

**Comment by PlasmaPower** [comment] 2016-04-23 13:44
@wind0204 I'm not using the EFI stub, as whenever linux updates the hash changes I think. Instead, I'm using systemd-boot (you should try that, the menu is optional).

**Comment by wind0204** [comment] 2016-04-23 17:27
@PlasmaPower it works so well, I appreciate it. :)

**Comment by PlasmaPower** [comment] 2016-04-23 17:28
@wind0204 Glad I could help!

**Comment by bobobo1618** [comment] 2016-08-05 05:00
Not sure if it helps anyone else ( @biggreenogre ? ) but I noticed that my SuperMicro X10SDV-F-O had a boot mode option in the BIOS boot config screen. It had the options "Legacy", "UEFI" and I think the last (and default) was something like "Hybrid".

Switched it to UEFI and it follows the boot order set in `efibootmgr`.

**Comment by biggreenogre** [comment] 2016-08-05 19:33
Thanks for the heads-up!

I downloaded and installed the latest BIOS for our systems (SS1028u-4+), X10DRU6.721, dated July of this year. Unfortunately, it seems that the UEFI Bootorder is still broken by their weird BIOS boot order menus.

Hopefully they have listened and fixed it on new systems going forward.

**Comment by MarCnu** [comment] 2016-08-16 18:19
I noticed something that hasn't been mentionned.

In the following commands, I change the boot order to put Ubuntu before Windows.

`$ efibootmgr 
BootCurrent: 0002
Timeout: 10 seconds
BootOrder: 0000,0002,0001
Boot0000* Windows Boot Manager
Boot0001  Hard Drive
Boot0002* ubuntu

$ sudo efibootmgr -o 0002,0000,0001
BootCurrent: 0002
Timeout: 10 seconds
BootOrder: 0002,0000,0001
Boot0000* Windows Boot Manager
Boot0001  Hard Drive
Boot0002* ubuntu

$ efibootmgr
BootCurrent: 0002
Timeout: 10 seconds
show_boot_order(): Permission denied
Boot0000* Windows Boot Manager
Boot0001  Hard Drive
Boot0002* ubuntu

$ sudo efibootmgr 
BootCurrent: 0002
Timeout: 10 seconds
BootOrder: 0002,0000,0001
Boot0000* Windows Boot Manager
Boot0001  Hard Drive
Boot0002* ubuntu`

Before the update, the boot order is visible without `sudo`. After the update, the boot order is only visible with `sudo`. Without `sudo`, you get `show_boot_order(): Permission denied`.

Maybe `efibootmgr` is changing the reading rights and after the reboot, as the BIOS cannot read the boot order, it resets it to default.

Anyway, there is something weird with the way `efibootmgr` works.

**Comment by TerpSte** [comment] 2016-09-04 11:57
I can confirm the same behavior here. After I updated the order, only `sudo efibootmgr` is able to read it, as @MarCnu mentions. Has anyone come up with a more permanent solution?

Laptop HP 250 G4
Motherboard HP 80C1
Windows 10 and Ubuntu 16.04
efibootmgr 0.12-4

**Comment by ForsakenHarmony** [comment] 2016-10-07 21:46
@MarCnu for me even without lists the correct order, but still doesn't work, probably bios related, if I try to change the order in bios a window with the options opens, but if I press enter the window flashes, but stays open

**Comment by mlen** [comment] 2016-10-11 06:18
For me (using T460 Thinkpad) the boot option doesn't even show up in EFI boot selection menu and the boot order is always reset to default after reboot, however setting bootnext works

**Comment by mlen** [comment] 2016-10-11 06:29
Huh, turns out I overlooked “Lock Boot Order” setting in setup menu. Disabling it allows to create new boot entries

**Comment by ForsakenHarmony** [comment] 2016-10-11 14:52
@mlen in bios?

**Comment by mlen** [comment] 2016-10-11 16:06
@ForsakenHarmony yep

**Comment by QiBaobin** [comment] 2016-12-28 02:27
@PlasmaPower , thanks, your solution works well on my acer travel mate.

**Comment by JonathonReinhart** [comment] 2017-02-03 19:36
I experienced this on a laptop with AMI firmware. I would remove a boot entry with `efibootmgr -B -b 0000` (Fedora), and confirm they happened with `efibootmgr -v`. But then when I rebooted, I'd see that `Boot0000` (Fedora) was back like I never did anything.

Then I noticed that the following variables existed:
- `FastBootOption` - Hexdump showed `shim.efi`, but not "Fedora"
- `FBO_SavedBootOrder` - (0, 3)
- `FBO_SavedBoot0000` - Looked just like the original `Boot0000`

I deleted these variables (`rm /sys/firmware/efi/efivars/...`) and then the system acted like I expected.

**Comment by RigDillinger** [comment] 2017-03-29 15:50
Greetings. Experienced this issue on old acer laptop.
I'm using arch linux.
'Fixed' by replacing /boot/efi/EFI/Microsoft/Boot/bootmgfw.efi with /boot/efi/EFI/arch/grubx64.efi
Having renamed that file allowed to boot straight to grub, without breaking Windows entry there.

**Comment by pa-kos** [comment] 2017-04-19 21:02
Fixed it on an **Acer** notebook ([StackExchane - AskUbuntu)](https://askubuntu.com/questions/771455/dual-boot-on-acer-aspire-es-15-es1-531-c13g):  

> Set supervisor password from Security menu option.
> Set BootMode to 'UEFI' from Boot menu option.
> Enable SecureBoot from Boot menu option.
> From Security menu option - Select 'UEFI file as trusted for
> executing' press Enter then 'HDD0' appears press Enter then 'EFI'
> appears press Enter then select 'ubuntu' option from the list (only
> listed if you have ubuntu installed already) press Enter then choose 'shimx64.efi' (In my case it's the third entry) press Enter give it a name and press Enter.
> Go back to Boot menu option and under Boot priority goto
> 'ubuntu' item in the list and press F6 until it become top most item in the list. Repeat same for 'Windows Boot manager' until it becomes second top most item in the list.
> Press F10 to save changes and exit.

**Comment by Redrield** [comment] 2017-08-04 02:28
I'm having much the same problem, though it seems to have f**ked me over a tad more.

I'm running dual booted Windows 10 and Manjaro Linux. In order to boot into grub after installation, I booted into windows and used bcdedit to modify the bootmgr path to point at the GRUB binary.

When I wanted to get rid of windows 10, I was told to use efibootmgr to modify the boot order to boot Manjaro first. When I did that and rebooted, I booted into Windows directly.

I managed to get back into Manjaro through my f12 boot menu, and efibootmgr output shows 2 Windows boot manager entries, one at 0000 and one at 0005, with 0000 being the first to boot. it seems this phantom WBM is also completely ignoring bcdedit, and choosing to boot directly to windows.

I reallllly need to get this fixed, so if anyone has any ideas I'd be glad to try them

**Comment by ramcq** [comment] 2017-08-04 09:48
@Redrield It sounds like the firmware is automatically creating an entry for Windows after finding the Windows EFI binary on the ESP (EFI System Partition), and placing it at the top of the list. This is unfortunately very common and utterly broken behaviour, but it's implemented in the firmware before any EFI binaries are run, so it's not something that efibootmgr can do anything about.

If you never want to boot Windows again on this machine, you could mount the ESP from under Linux and just remove the Microsoft/Windows directories from the ESP, then clean up efibootmgr entries. If you do want Windows to boot but not be the default, I think the safest thing to do is try and use the firmware settings to change the boot order to place Linux first, and then never touch it again from efibootmgr/bcdedit - that's most likely to "stick".

**Comment by Redrield** [comment] 2017-08-04 16:13
@ramcq If you mean in the configuration options that I get when I use f2 at boot, i can't. The only options in the boot order there are to generically boot from my HDD, boot from windows boot manager, or net boot and other external boot sources.

**Comment by omcira** [comment] 2017-10-07 21:16
Solved on my Acer Spin 5 SP513-51-54F6 in a similar way as @JonathonReinhart: by making a backup of /boot/efi/EFI/Microsoft/Boot/bootmgfw.efi, then changing it with the grubx64.efi executable, and than making a new entry in grub for windows that points to the backup of bootmgfw.efi.

**Comment by douglaslaraa** [comment] 2017-12-20 00:55
@RigDillinger Thanks resolved for me.

**Comment by odomobo** [comment] 2018-01-07 22:34
@RigDillinger 's fix worked for me also. I'm using an Acer Aspire E5-575-33BM.

I wanted a linux-only boot system. I moved my .efi file from its linux-specific path to /EFI/Microsoft/Boot/bootmgfw.efi , on the efi partition. I didn't need to add the boot option using efibootmgr, the entry was there automatically on start. It shows up as "Windows Boot Manager".

**Comment by mattia-b89** [comment] 2018-01-22 21:41
I am on a Dell XPS 9343 (bios A14)
I experience a similar problem: I can manage with boot entries, boot order, timeout with `efibootmgr` but when I reboot, settings are resetted to the original values.
I have only Arch Linux installed on my disk.

**Comment by mattia-b89** [comment] 2018-01-26 15:11
I am on a Dell XPS 9343 (bios A14) and I experience a similar problem: I can manage with boot entries, boot order, timeout with `efibootmgr` but when I **reboot**, settings are resetted to their original values.

I have only Arch Linux installed on my disk.

**Comment by cmurf** [comment] 2018-04-19 20:12
HP Spectre has started ignoring BootOrder recently. I suspect a recent firmware update is what broke it. I've tried minimal regression testing kernel 4.14.18, 4.15.14, and 4.16.2 with efibootmgr-15-3 and 15-6 and it's all the same. BootNext works, but changing either the BootOrder variable with efibootmgr --bootorder or PhysicalBootOrder per this bug's advice https://bugzilla.redhat.com/show_bug.cgi?id=1343559#c5 does not work.

I do before and after hexdump -C for each of the variables, if that is a reliable check of whether the change is really written to NVRAM, then that means on reboot the firmware is somehow resetting those variables - but I don't understand what BootOrder can use as a template. In such a case I'd expect it to revert to Windows, but I'm trying to get the BootOrder to make Window first, but instead I'm always getting GRUB (the Fedora entry).

**Comment by bvrulez** [comment] 2018-11-01 10:55
I have a similar problem with my Shuttle Barebone XPC Cube SH170R6 1151. I have Lubuntu 18.10 running and added a Win10. It all works fine except Win10 is booting as default. I can change via F7/boot menu to Ubuntu. I have secure boot deactivated. I tried to use [rEFInd](http://www.rodsbooks.com/refind/installing.html#linux) as bootmanager and found that after I setup the entry with efibootmgr and sudo it gets changed again on reboot. Did not try and workarounds yet.

**Comment by kenogo** [comment] 2019-03-10 11:51
Same behavior on an msi x470 motherboard

**Comment by DheathNone** [comment] 2019-04-28 19:48
Same behavior observed on a Microsoft surface go.

**Comment by zviratko** [comment] 2019-05-21 20:30
Asrock X470 Taichi Ultimate- also braindead.
Oh, and Asrock apparently "Only support Windows OS" (haven't heard that one in a while!)

**Comment by MycroftHolmes1989** [comment] 2019-09-11 16:51
Asus X370-F. Cannot remove EFI entries. Can create new ones, but existing EFI entries cannot be removed.

**Comment by emagin-es** [comment] 2019-12-15 20:48
> Greetings. Experienced this issue on acer laptop.
> I'm using arch linux.
> 'Fixed' by replacing `/boot/efi/EFI/Microsoft/Boot/bootmgfw.efi` with `/boot/efi/EFI/arch/grubx64.efi`
> Having **renamed** that file allowed to boot straight to grub without breaking Windows entry there and playing around with `efibootmgr`

It works, thank you very much!!

**Comment by sirtomato999** [comment] 2020-01-17 22:31
also happens with a Asus PRIME a320m-a even after I updated the BIOS

**Comment by xiconfjs** [comment] 2020-03-06 00:36
For every Supermicro X10 (X11 should be the same) user which can't set the uefi boot order from linux with efibootmgr:

It' not your fault - it's Supermicro's fault -> [1]. They prohibit the change of the boot order from non-windows or non-signed-kernel systems. They offer an option to set the boot order via SUM (Supermicro Update Manager) -> [2] but this is way to complicated.

Easy way via BIOS:

1. Enter BIOS
2. Go to **Boot**
3. Select **Add new boot option**
4. Select **Add boot option**
5. Give the boot option a meaningful name
6. Select **Path for boot option**
7. Select the drive/volume the efi image is located
8. Then there is a "popup" titled **Select a File to Boot** which leads you through the directory tree of the drive/volume until you reach the efi image. At the end select the appropriate efi image - e.x. **grubx64.efi**
9. Select **Create** to finish which should verify the successful process with the "popup" **Boot Option Created Successfully**
10. Now go to **Save & Exit** and select **Save Changes and Reset**
11. After reset enter the BIOS again
12. Go to **Boot** 
13. Select **UEFI Hard Disk Drive BBS Priorities**
14. Select **UEFI Boot Order #1** and select your newly created boot option
15. Now go to **Save & Exit** and select **Save Changes and Reset** and it should boot your selected OS.

I attached a slideshow-style screencast so the youth can follow my directions. If anybody want to put this on his/her blog/instagram/whateverIsCoolToday - feel free - but please link to this comment.


[1] https://www.supermicro.com/support/faqs/faq.cfm?faq=27004
[2] https://www.supermicro.com/SwDownload/UserInfo.aspx?sw=0&cat=SUM
<img width="804" alt="01" src="https://user-images.githubusercontent.com/488828/76038775-cd038500-5f4a-11ea-94fc-f50f9874544d.png">
<img width="804" alt="02" src="https://user-images.githubusercontent.com/488828/76038781-d1c83900-5f4a-11ea-8b51-498d2b9ddd3f.png">
<img width="805" alt="03" src="https://user-images.githubusercontent.com/488828/76038782-d260cf80-5f4a-11ea-812e-4537d94ef83f.png">
<img width="803" alt="04" src="https://user-images.githubusercontent.com/488828/76038783-d2f96600-5f4a-11ea-96fc-7b0ff37e9818.png">
<img width="805" alt="05" src="https://user-images.githubusercontent.com/488828/76038785-d391fc80-5f4a-11ea-8d64-777646ae84d0.png">
<img width="803" alt="06" src="https://user-images.githubusercontent.com/488828/76038786-d42a9300-5f4a-11ea-9125-da976a7c42f8.png">
<img width="806" alt="07" src="https://user-images.githubusercontent.com/488828/76038790-d55bc000-5f4a-11ea-877b-cf0453f6c7b5.png">
<img width="804" alt="08" src="https://user-images.githubusercontent.com/488828/76038792-d5f45680-5f4a-11ea-9f04-c31b2e1b9569.png">
<img width="805" alt="09" src="https://user-images.githubusercontent.com/488828/76038794-d68ced00-5f4a-11ea-8991-16a56a9469be.png">
<img width="805" alt="10" src="https://user-images.githubusercontent.com/488828/76038796-d7be1a00-5f4a-11ea-97a5-f415a4773755.png">
<img width="803" alt="11" src="https://user-images.githubusercontent.com/488828/76038797-d856b080-5f4a-11ea-93e2-3a684d8c5326.png">
<img width="804" alt="12" src="https://user-images.githubusercontent.com/488828/76038799-d987dd80-5f4a-11ea-8566-7995c9377fd4.png">

**Comment by alan12345678** [comment] 2020-04-30 14:16
I don't have an 'issue' with **efibootmgr** either - as per above posts this is about the odd removal of my boot entries after a lengthy shutdown. I found the above comments very helpful, as having been about to re-flash my bios it hadn't occurred to me to actually enable secure boot!

Reason I mention this is because having done so (and it's too early to tell yet whether settings will persist. I'll know tomorrow morning) I wasn't asked for any passwords or to confirm or accept anything as 'trusted' or 'secure' ?

I might point out that when installing on this ex Windows 8.1 box I deleted all the partition information. This is a single system, single user machine, with Arch linux on it. I began afresh with new GPT table, and then entries and formatting accordingly.

I've just started booting via efistub, having ditched grub2 because why do I need another bootloader? Had same issues when using grub i.e. settings lost overnight. I've tried CSM support both on and off, as per other answers elsewhere, but same difference.

I have no problem editing boot entries, or creating a new one in **efibootmgr** but obviously it's a complete pain in the **s having to rewrite that every morning!

**Comment by Shinigami92** [comment] 2020-08-29 18:22
After several HOURS I managed to write the entry manually with bcfg: https://wiki.archlinux.org/index.php/Unified_Extensible_Firmware_Interface#bcfg

1. `map`
   my SSD was `FS1:`
   found out via `FS1:` + `ls` => _has EFI directory_ (don't get confused with arch iso live CD!!!)
2. `bcfg boot add 3 FS1:\EFI\refind\refind_x64.efi "rEFInd Boot Manager"` 
3. `bcfg boot mv 3 0`
4. profit $$$

**Comment by Sporknife** [comment] 2020-09-26 22:16
Issue still present on Asus prime z370-p with the latest bios. The boot order just *dissapears*.

**Comment by motorto** [comment] 2020-12-09 23:03
Just want to comment that on my Acer aspire vn7-591g this issue occurs .

Not using windows , just linux but as soon as I plug a bootable usb (linux one for example) automatically boots ftom that and the infamous boot0000 appears at the first place on boot order.

Using UEFI with secure boot enable, didn't try the legacy mode.

**Comment by NgoHuy** [comment] 2020-12-28 13:49
After upgrading bios firmware, all linux boot order has gone But windows's still alive. How can we keep it after upgrading bios firmware?

**Comment by martinezjavier** [comment] 2021-06-17 09:01
There are a lot of comments about broken EFI firmware behavior in this issue, but none of the problems are related to efibootmgr. So I'm closing this.

**Closed by martinezjavier** 2021-06-17 09:01 UTC

**Comment by Varun-garg** [comment] 2022-02-13 08:59
Some observations I had on a B550 motherboard, might help others in this thread:

1. During boot, firmware starts reading entries in order
2. If it finds an entry with a duplicate name but with the same path and params, it skips and deletes it.
3. If it finds an entry with an invalid path or params, it skips and deletes it.
4. If an entry exists but is not a part of the boot order, it skips but does not delete it.

**Comment by emagin-es** [comment] 2022-02-13 09:03
Good morning.
Some days ago I found the solution.
https://ubuntuforums.org/showthread.php?t=2297947
I hope you find it useful.
Regards.

**Comment by GogoFC** [comment] 2025-02-02 04:40
> For every Supermicro X10 (X11 should be the same) user which can't set the uefi boot order from linux with efibootmgr:
> 
> It' not your fault - it's Supermicro's fault -> [1]. They prohibit the change of the boot order from non-windows or non-signed-kernel systems. They offer an option to set the boot order via SUM (Supermicro Update Manager) -> [2] but this is way to complicated.
> 

Four years later. I couldn't get Proxmox to boot from this board off of two Samsung EVO 870s. SAS HDDs worked fine.
