### ISSUE TITLE
Changes made by efibootmgr --bootorder are being reset after restarting the computer

### ISSUE THREAD

**Issue by BoQsc** [rhboot/efibootmgr#130] opened 2020-04-21 21:13 UTC
## Hardware Information
Laptop: Toshiba L855-14E
Embedded controller (EC): 6.20 version
System BIOS Version: 6.70
- Insydeh20 rev3.7 Setup Utility

## Information about system
```
vaidas@vaidas-SATELLITE-L855:~$ efibootmgr --version
version 15
vaidas@vaidas-SATELLITE-L855:~$ uname -a
Linux vaidas-SATELLITE-L855 5.3.0-46-generic #38-Ubuntu SMP Fri Mar 27 17:37:05 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
vaidas@vaidas-SATELLITE-L855:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 19.10
Release:	19.10
Codename:	eoan
```

## Walkthrough
```
vaidas@vaidas-SATELLITE-L855:~$ efibootmgr 
BootCurrent: 0001
Timeout: 2 seconds
BootOrder: 0000,0001,2001,2002,2003
Boot0000* Windows Boot Manager
Boot0001* Ubuntu
Boot2001* EFI USB Device
Boot2002* EFI DVD/CDROM
Boot2003* EFI Network
vaidas@vaidas-SATELLITE-L855:~$ sudo efibootmgr --bootorder 0001,0000,2001,2002,2003
[sudo] password for vaidas: 

BootCurrent: 0001
Timeout: 2 seconds
BootOrder: 0001,0000,2001,2002,2003
Boot0000* Windows Boot Manager
Boot0001* Ubuntu
Boot2001* EFI USB Device
Boot2002* EFI DVD/CDROM
Boot2003* EFI Network

```

As you can see everything is correct.  
But after restarting the Laptop is still booting to Windows Boot Manager.
If you load Ubuntu instead, you can see that the Boot Order is reseted.

```
vaidas@vaidas-SATELLITE-L855:~$ efibootmgr 
BootCurrent: 0001
Timeout: 2 seconds
BootOrder: 0000,0001,2001,2002,2003
Boot0000* Windows Boot Manager
Boot0001* Ubuntu
Boot2001* EFI USB Device
Boot2002* EFI DVD/CDROM
Boot2003* EFI Network
```

**Comment by djuarezg** [comment] 2020-08-18 12:20
This seems like a duplicate of https://github.com/rhboot/efibootmgr/issues/19

And yes, I am facing this issue myself as well with no workaround at this moment.

**Comment by dag7dev** [comment] 2020-09-25 09:10
I can confirm the issue is still present.

**Comment by Sporknife** [comment] 2020-09-26 22:17
Issue still present on Asus prime z370-p with the latest bios. The boot order just *disappears*.

**Comment by martinezjavier** [comment] 2021-06-17 10:14
Closing since this is a problem with the firmware, not efibootmgr.

**Closed by martinezjavier** 2021-06-17 10:14 UTC
